### ISSUE TITLE
Statusabfrage über origName

### ISSUE THREAD

**Issue by lambdafu** [da-nrw/DNSCore#14]
Hi,

ich probier gerade mal die Statusabfrage aus:

Funktioniert: https://eunomia.hbz-nrw.de/daweb3/status/index?identifier=3-2015032444366

Funktioniert: https://eunomia.hbz-nrw.de/daweb3/status/index?urn=urn:nbn:de:hbz:6:1-15604

Funktioniert nicht: https://eunomia.hbz-nrw.de/daweb3/status/index?origName=urn+nbn+de+hbz+6+1-15604

Letzteres liefert {"status":"not found"}.

Ist der origName eigentlich der Name des ausgepackten Verzeichnisses?

**Comment by jenspeters** [comment]
Hallo,

da urn+nbn+de+hbz+6+1-15604 der origName laut DB ist, sollte dies auch zu einem identischen Ergebnis führen (wurde so auch getestet). Ich vermute, dass da irgendein unbeabsichtigtes auto-decoding zuschlägt. 

Können Sie ggfs. ein Ticket auf JIRA aufmachen? 
Danke , Grüße

**Comment by jenspeters** [comment]
Hallo,

bitte das URL Sonderzeichen "+" als %2B enkodiert übergeben. Bei unserer Teststellung funktioniert das. 

Grüße

**Comment by lambdafu** [comment]
Das entspricht aber nicht den RFC Standards.
