### ISSUE TITLE
SIPBuilder failes to create tgz archive sometimes

### ISSUE THREAD

**Issue by Possommi** [da-nrw/DNSCore#33]
Sometimes the SIPBuilder failes to create tgz-archives with the following error message:

java.io.IOException: This archive contains unclosed entries.
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:289)
	at de.uzk.hki.da.pkg.SipArchiveBuilder.archiveFolder(SipArchiveBuilder.java:97)
	at de.uzk.hki.da.sb.SIPFactory.buildArchive(SIPFactory.java:602)
	at de.uzk.hki.da.sb.SIPFactory.packageFolder(SIPFactory.java:317)
	at de.uzk.hki.da.sb.SIPFactory.buildSIP(SIPFactory.java:276)
	at de.uzk.hki.da.sb.SIPFactory.access$1300(SIPFactory.java:69)
	at de.uzk.hki.da.sb.SIPFactory$SipBuildingProcess.run(SIPFactory.java:1086)

**Comment by Possommi** [comment]
Using the -noCompression option fixes this issue.

**Comment by jenspeters** [comment]
Hey there, could you please elaborate a little bit under which circumstances this may happen? We could not reproduce this issue until now.

**Comment by Possommi** [comment]
I could provide the content directory from which the SIP should be build.

**Comment by trebunski** [comment]
Can this issue be reproduced by using your "content directory"?

**Comment by Possommi** [comment]
In production the SIP-Builder is invoked from a JVM and the sip building failes reproducable. 
If I invoke the SIP-Builder direct from command line everything works fine.

**Comment by trebunski** [comment]
Its hard to analyse this Issue, because we can't reproduce it.
- Can you provide a minimal amount of code that is very minimal but large enough to reproduce this error?

- Does this problem require your special "content directory" or fails it on any data directory as long as it is called by JVM?

**Comment by trebunski** [comment]
Hello I can't reproduce it. Can You adapt my code snippet (rename it to .java, github block java attachments), until You get IOException and, if necessary, attach your sip-contents.  

[SIPBuilderJobAction.txt](https://github.com/da-nrw/DNSCore/files/3743475/SIPBuilderJobAction.txt)


PS: I mainly copy pastet it from mycore source code, I guess You get your errors by use this class [SIPBuilderJobAction]( https://fisheye.mycore.de/browse/Thulb-Maven-SVN/collections/collections-module/src/main/java/de/uni_jena/thulb/archive/sip/SIPBuilderJobAction.java?r1=4089&r2=4089&u=3 )

**Comment by trebunski** [comment]
Maybe this Issue happens only due to specific system configuration, e.g. network attached storage.
You can try to pass local working path by use the "-workspace" argument to ensure SipBuilder does not work on network attached storage (in most cases if workspace is not localy attached, sip building is slower)

**Comment by Possommi** [comment]
it is working on the same storage when I invoke the SIPBuilder manually. The problem only occures if the SIPBuilder is invoked from another web application. Since using the -noCompression flag fixes this issue I will use this from now on.
